notifications:
 email:
  recipients:
   - pierrick.roger@gmail.com
                           
before_install:
 - sudo apt-get install -y python-virtualenv
 - sudo apt-get install -y ant
 - sudo apt-get install -y r-base
 - sudo R -e "install.packages(c('getopt', 'stringr'), dependencies = TRUE, repos='http://lib.ugent.be/CRAN/')"
 - virtualenv planemo-venv
 - . planemo-venv/bin/activate
 - pip install --upgrade pip setuptools
 - pip install planemo
 - planemo --version

script:
 - ant galaxy.test
