---
- hosts: all
  vars:
    crandeb_repos: "http://mirrors.ebi.ac.uk/CRAN/bin/linux/ubuntu trusty/"
    crandeb_key: E084DAB9

  tasks:
    - name: Add CRAN to package repositories
      lineinfile: dest=/etc/apt/sources.list state=present line="deb {{crandeb_repos}}"

    - name: Request CRAN key from Ubuntu
      command: gpg --keyserver keyserver.ubuntu.com --recv-key {{crandeb_key}}

    - name: Add CRAN key to apt keys
      shell: gpg -a --export {{crandeb_key}} | apt-key add -

    - name: Update package database
      apt: update_cache=yes

    - name: Upgrade packages
      apt: upgrade=yes

    - name: Install R
      apt: pkg={{ item }} state=latest
      when: ansible_os_family == 'Debian'
      with_items:
        - r-base

#    - name: Install R package getopt
#      command: "R -e \"install.packages('getopt', dependencies = TRUE, repos='http://lib.ugent.be/CRAN/')\""
#
#    - name: Install R package stringr
#      command: "R -e \"install.packages('stringr', dependencies = TRUE, repos='http://lib.ugent.be/CRAN/')\""
#
#    - name: Install R package plyr
#      command: "R -e \"install.packages('plyr', dependencies = TRUE, repos='http://lib.ugent.be/CRAN/')\""
