---
- hosts: all
  vars:
    crandeb_repos: "http://mirrors.ebi.ac.uk/CRAN/bin/linux/ubuntu trusty/"
    crandeb_key: E084DAB9

  tasks:
    - name: Add CRAN to package repositories
      lineinfile: dest=/etc/apt/sources.list state=present line="deb {{crandeb_repos}}"

    - name: Request CRAN key from Ubuntu
      command: gpg --keyserver keyserver.ubuntu.com --recv-key {{crandeb_key}}

    - name: Add CRAN key to apt keys
      shell: gpg -a --export {{crandeb_key}} | apt-key add -

    - name: Update package database
      apt: update_cache=yes

    - name: Upgrade packages
      apt: upgrade=yes

    - name: Install R
      apt: pkg={{ item }} state=latest
      when: ansible_os_family == 'Debian'
      with_items:
        - r-base

    - name: Install R package getopt
      command: R -e "install.packages('getopt', lib='/usr/lib/R/library', dependencies = TRUE, repos='http://lib.ugent.be/CRAN/')" creates=/usr/lib/R/library/getopt

    - name: Install R package stringr
      command: R -e "install.packages('stringr', lib='/usr/lib/R/library', dependencies = TRUE, repos='http://lib.ugent.be/CRAN/')" creates=/usr/lib/R/library/stringr

    - name: Install R package plyr
      command: R -e "install.packages('plyr', lib='/usr/lib/R/library', dependencies = TRUE, repos='http://lib.ugent.be/CRAN/')" creates=/usr/lib/R/library/plyr

    - name: Install library dependencies for XML CRAN package
      apt: pkg={{ item }} state=latest
      when: ansible_os_family == 'Debian'
      with_items:
        - libcurl4-openssl-dev
        - libxml2-dev

    - name: Install R package XML
      command: R -e "install.packages('XML', lib='/usr/lib/R/library', dependencies = TRUE, repos='http://lib.ugent.be/CRAN/')" creates=/usr/lib/R/library/XML
